<a href="https://colab.research.google.com/github/Nibaron/Neural-Network-LAB/blob/main/KOHONEN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import math
import numpy as np
import random

In [ ]:
v = int(input("Enter Vector Size : "));
c = int(input("Enter Cluster Size : "));

Enter Vector Size : 4
Enter Cluster Size : 2


In [ ]:
#vector_initialization
vector=np.random.choice([0, 1], size=(v,v))
print(vector)

[[0 1 0 1]
 [0 0 0 0]
 [1 0 0 1]
 [0 0 1 0]]


In [ ]:
#weight_initialization
weight= np.random.random(size=(v,c))
print(weight)

[[0.51959779 0.23263248]
 [0.99042529 0.47132332]
 [0.50886055 0.77514779]
 [0.9677816  0.41115787]]


In [ ]:
#distance_initialization
d=np.random.random(size=(c))
for i in range(c):
  d[i]=0.0
print(d)

[0. 0.]


In [ ]:
#1st vector and 1st weight pair
for i in range(v):
  print(vector[0][i])
  print(weight[i][0])

0
0.519597789546938
1
0.9904252932484031
0
0.5088605483462418
1
0.9677815974217402


In [ ]:
#1st vector and 2nd weight pair
for i in range(v):
  print(vector[0][i])
  print(weight[i][1])

0
0.23263248288855198
1
0.4713233179423453
0
0.775147789446159
1
0.41115786636790286


In [ ]:
#distance and weight update
print(weight)
print()
alpha=0.5
for m in range(v):
  print("for  Vector Input: ",m)
  for i in range(c):
    for j in range(v):
      d[i] = d[i] + math.pow((vector[m][j]-weight[j][i]),2);
  print("Euclidian Distances array: ")
  print(d)
  wc=np.argmin(d)
  print("winning Cluster Index:",wc)
  for i in range(c):
     d[i]=0.0
  for i in range(v):
    weight[i][wc] = weight[i][wc] + alpha*(vector[m][i]-weight[i][wc]) 
  print("Weight after  update:")
  print(weight)
  print()
  print()
print("The Final weights are:")
print(weight)

[[0.51959779 0.23263248]
 [0.99042529 0.47132332]
 [0.50886055 0.77514779]
 [0.9677816  0.41115787]]

for  Vector Input:  0
Euclidian Distances array: 
[0.53005062 1.28120606]
winning Cluster Index: 0
Weight after  update:
[[0.25979889 0.23263248]
 [0.99521265 0.47132332]
 [0.25443027 0.77514779]
 [0.9838908  0.41115787]]


for  Vector Input:  1
Euclidian Distances array: 
[2.09071955 1.04616843]
winning Cluster Index: 1
Weight after  update:
[[0.25979889 0.11631624]
 [0.99521265 0.23566166]
 [0.25443027 0.38757389]
 [0.9838908  0.20557893]]


for  Vector Input:  2
Euclidian Distances array: 
[1.60334016 1.61775176]
winning Cluster Index: 0
Weight after  update:
[[0.62989945 0.11631624]
 [0.49760632 0.23566166]
 [0.12721514 0.38757389]
 [0.9919454  0.20557893]]


for  Vector Input:  3
Euclidian Distances array: 
[2.39009446 0.48639432]
winning Cluster Index: 1
Weight after  update:
[[0.62989945 0.05815812]
 [0.49760632 0.11783083]
 [0.12721514 0.69378695]
 [0.9919454  0.10278947]]


Th